// AUTO-GENERATED by scripts/generate_tabular_script.py — do not edit by hand.
// Tabular Editor 2 (free): connect to the Epikast model, Advanced Scripting, Run (F5), Save.
// Creates 139 measures, 6 calculated columns, 15 relationships.

int mAdded = 0, cAdded = 0, rAdded = 0;

// ---- _Measures host table ----
var mt = Model.Tables.Contains("_Measures") ? Model.Tables["_Measures"]
    : Model.AddCalculatedTable("_Measures", "{BLANK()}");

// ---- Measures ----
try {
    var m = mt.Measures.Contains(@"Total Calls") ? mt.Measures[@"Total Calls"] : mt.AddMeasure(@"Total Calls");
    m.Expression = @"COUNTROWS(FactHCPCalls)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connected Calls") ? mt.Measures[@"Connected Calls"] : mt.AddMeasure(@"Connected Calls");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[IsConnected] = 1)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connected Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate") ? mt.Measures[@"Connect Rate"] : mt.AddMeasure(@"Connect Rate");
    m.Expression = @"DIVIDE([Connected Calls], [Total Calls], 0)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Meaningful Interactions") ? mt.Measures[@"Meaningful Interactions"] : mt.AddMeasure(@"Meaningful Interactions");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[IsMeaningfulInteraction] = 1)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Meaningful Interactions -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Meaningful Interaction Rate") ? mt.Measures[@"Meaningful Interaction Rate"] : mt.AddMeasure(@"Meaningful Interaction Rate");
    m.Expression = @"DIVIDE([Meaningful Interactions], [Connected Calls], 0)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Meaningful Interaction Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"HCPs Contacted") ? mt.Measures[@"HCPs Contacted"] : mt.AddMeasure(@"HCPs Contacted");
    m.Expression = @"DISTINCTCOUNT(FactHCPCalls[HCPID])";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: HCPs Contacted -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Target HCPs") ? mt.Measures[@"Target HCPs"] : mt.AddMeasure(@"Target HCPs");
    m.Expression = @"CALCULATE(DISTINCTCOUNT(DimHCP[HCPID]), DimHCP[IsTarget] = 1)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Target HCPs -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"HCP Reach") ? mt.Measures[@"HCP Reach"] : mt.AddMeasure(@"HCP Reach");
    m.Expression = @"DIVIDE(CALCULATE(DISTINCTCOUNT(FactHCPCalls[HCPID]), FactHCPCalls[IsConnected] = 1), [Target HCPs], 0)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: HCP Reach -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Contact Frequency") ? mt.Measures[@"Avg Contact Frequency"] : mt.AddMeasure(@"Avg Contact Frequency");
    m.Expression = @"DIVIDE([Connected Calls], [HCPs Contacted], 0)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Contact Frequency -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Call Duration") ? mt.Measures[@"Avg Call Duration"] : mt.AddMeasure(@"Avg Call Duration");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[DurationMinutes]), FactHCPCalls[IsConnected] = 1)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Call Duration -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Meaningful Duration") ? mt.Measures[@"Avg Meaningful Duration"] : mt.AddMeasure(@"Avg Meaningful Duration");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[DurationMinutes]), FactHCPCalls[IsMeaningfulInteraction] = 1)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Meaningful Duration -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Follow Up Rate") ? mt.Measures[@"Follow Up Rate"] : mt.AddMeasure(@"Follow Up Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[FollowUpScheduled] = 1), [Connected Calls], 0)";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Follow Up Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg HCP Sentiment") ? mt.Measures[@"Avg HCP Sentiment"] : mt.AddMeasure(@"Avg HCP Sentiment");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[HCPSentimentScore]), NOT(ISBLANK(FactHCPCalls[HCPSentimentScore])))";
    m.DisplayFolder = @"HCP Engagement";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg HCP Sentiment -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Recommended Calls") ? mt.Measures[@"AI Recommended Calls"] : mt.AddMeasure(@"AI Recommended Calls");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[AIRecommended] = 1)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Recommended Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Followed Calls") ? mt.Measures[@"AI Followed Calls"] : mt.AddMeasure(@"AI Followed Calls");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[AIFollowed] = 1)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Followed Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Acceptance Rate") ? mt.Measures[@"AI Acceptance Rate"] : mt.AddMeasure(@"AI Acceptance Rate");
    m.Expression = @"DIVIDE([AI Followed Calls], [AI Recommended Calls], 0)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Acceptance Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Connect Rate") ? mt.Measures[@"AI Connect Rate"] : mt.AddMeasure(@"AI Connect Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[AIFollowed] = 1, FactHCPCalls[IsConnected] = 1), [AI Followed Calls], 0)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Non-AI Connect Rate") ? mt.Measures[@"Non-AI Connect Rate"] : mt.AddMeasure(@"Non-AI Connect Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[AIRecommended] = 0, FactHCPCalls[IsConnected] = 1), CALCULATE([Total Calls], FactHCPCalls[AIRecommended] = 0), 0)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Non-AI Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Lift on Connect Rate") ? mt.Measures[@"AI Lift on Connect Rate"] : mt.AddMeasure(@"AI Lift on Connect Rate");
    m.Expression = @"[AI Connect Rate] - [Non-AI Connect Rate]";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Lift on Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Meaningful Rate") ? mt.Measures[@"AI Meaningful Rate"] : mt.AddMeasure(@"AI Meaningful Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[AIFollowed] = 1, FactHCPCalls[IsMeaningfulInteraction] = 1), CALCULATE([Total Calls], FactHCPCalls[AIFollowed] = 1, FactHCPCalls[IsConnected] = 1), 0)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Meaningful Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Non-AI Meaningful Rate") ? mt.Measures[@"Non-AI Meaningful Rate"] : mt.AddMeasure(@"Non-AI Meaningful Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[AIRecommended] = 0, FactHCPCalls[IsMeaningfulInteraction] = 1), CALCULATE([Total Calls], FactHCPCalls[AIRecommended] = 0, FactHCPCalls[IsConnected] = 1), 0)";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Non-AI Meaningful Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AI Lift on Meaningful Rate") ? mt.Measures[@"AI Lift on Meaningful Rate"] : mt.AddMeasure(@"AI Lift on Meaningful Rate");
    m.Expression = @"[AI Meaningful Rate] - [Non-AI Meaningful Rate]";
    m.DisplayFolder = @"AI / Next-Best-Action";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AI Lift on Meaningful Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script A Calls") ? mt.Measures[@"Script A Calls"] : mt.AddMeasure(@"Script A Calls");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script A - Empathetic"")";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script A Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script B Calls") ? mt.Measures[@"Script B Calls"] : mt.AddMeasure(@"Script B Calls");
    m.Expression = @"CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script B - Direct"")";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script B Calls -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script A Connect Rate") ? mt.Measures[@"Script A Connect Rate"] : mt.AddMeasure(@"Script A Connect Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script A - Empathetic"", FactHCPCalls[IsConnected] = 1), [Script A Calls], 0)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script A Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script B Connect Rate") ? mt.Measures[@"Script B Connect Rate"] : mt.AddMeasure(@"Script B Connect Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script B - Direct"", FactHCPCalls[IsConnected] = 1), [Script B Calls], 0)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script B Connect Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script A Meaningful Rate") ? mt.Measures[@"Script A Meaningful Rate"] : mt.AddMeasure(@"Script A Meaningful Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script A - Empathetic"", FactHCPCalls[IsMeaningfulInteraction] = 1), CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script A - Empathetic"", FactHCPCalls[IsConnected] = 1), 0)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script A Meaningful Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script B Meaningful Rate") ? mt.Measures[@"Script B Meaningful Rate"] : mt.AddMeasure(@"Script B Meaningful Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script B - Direct"", FactHCPCalls[IsMeaningfulInteraction] = 1), CALCULATE([Total Calls], FactHCPCalls[Script] = ""Script B - Direct"", FactHCPCalls[IsConnected] = 1), 0)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script B Meaningful Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script A Avg Duration") ? mt.Measures[@"Script A Avg Duration"] : mt.AddMeasure(@"Script A Avg Duration");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[DurationMinutes]), FactHCPCalls[Script] = ""Script A - Empathetic"", FactHCPCalls[IsConnected] = 1)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script A Avg Duration -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script B Avg Duration") ? mt.Measures[@"Script B Avg Duration"] : mt.AddMeasure(@"Script B Avg Duration");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[DurationMinutes]), FactHCPCalls[Script] = ""Script B - Direct"", FactHCPCalls[IsConnected] = 1)";
    m.DisplayFolder = @"Script A/B Testing";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script B Avg Duration -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Cases") ? mt.Measures[@"Total Cases"] : mt.AddMeasure(@"Total Cases");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Cases -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Active Cases") ? mt.Measures[@"Active Cases"] : mt.AddMeasure(@"Active Cases");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[CaseStatus] IN {""Open"", ""In Progress""}, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Active Cases -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Resolved Cases") ? mt.Measures[@"Resolved Cases"] : mt.AddMeasure(@"Resolved Cases");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[CaseStatus] = ""Resolved"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Resolved Cases -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandoned Cases") ? mt.Measures[@"Abandoned Cases"] : mt.AddMeasure(@"Abandoned Cases");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[IsAbandoned] = 1, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandoned Cases -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandonment Rate") ? mt.Measures[@"Abandonment Rate"] : mt.AddMeasure(@"Abandonment Rate");
    m.Expression = @"DIVIDE([Abandoned Cases], [Total Cases], 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandonment Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Time to Therapy") ? mt.Measures[@"Avg Time to Therapy"] : mt.AddMeasure(@"Avg Time to Therapy");
    m.Expression = @"CALCULATE(AVERAGE(FactPatientCases[TimeToTherapyDays]), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Time to Therapy -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Median Time to Therapy") ? mt.Measures[@"Median Time to Therapy"] : mt.AddMeasure(@"Median Time to Therapy");
    m.Expression = @"CALCULATE(MEDIAN(FactPatientCases[TimeToTherapyDays]), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Median Time to Therapy -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"PA Approval Rate") ? mt.Measures[@"PA Approval Rate"] : mt.AddMeasure(@"PA Approval Rate");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[PAStatus] = ""Approved"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[PAStatus] IN {""Approved"", ""Denied"", ""Appeal""}, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])), 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: PA Approval Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"PA Denial Rate") ? mt.Measures[@"PA Denial Rate"] : mt.AddMeasure(@"PA Denial Rate");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[PAStatus] = ""Denied"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[PAStatus] IN {""Approved"", ""Denied"", ""Appeal""}, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])), 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: PA Denial Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg PA Decision Delay") ? mt.Measures[@"Avg PA Decision Delay"] : mt.AddMeasure(@"Avg PA Decision Delay");
    m.Expression = @"CALCULATE(AVERAGE(FactPatientCases[PADecisionDelayDays]), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg PA Decision Delay -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"First Call Resolution Rate") ? mt.Measures[@"First Call Resolution Rate"] : mt.AddMeasure(@"First Call Resolution Rate");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[FirstCallResolved] = 1, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    [Resolved Cases], 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: First Call Resolution Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Case Resolution Days") ? mt.Measures[@"Avg Case Resolution Days"] : mt.AddMeasure(@"Avg Case Resolution Days");
    m.Expression = @"CALCULATE(AVERAGE(FactPatientCases[CaseResolutionDays]), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Case Resolution Days -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg First Contact Delay") ? mt.Measures[@"Avg First Contact Delay"] : mt.AddMeasure(@"Avg First Contact Delay");
    m.Expression = @"CALCULATE(AVERAGE(FactPatientCases[FirstContactDelayDays]), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg First Contact Delay -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Contacted Within 48h Rate") ? mt.Measures[@"Contacted Within 48h Rate"] : mt.AddMeasure(@"Contacted Within 48h Rate");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[FirstContactDelayDays] <= 2, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    [Total Cases], 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Contacted Within 48h Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Adherence 30 Day") ? mt.Measures[@"Adherence 30 Day"] : mt.AddMeasure(@"Adherence 30 Day");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[Adherent30] = 1, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[Adherent30])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])), 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Adherence 30 Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Adherence 60 Day") ? mt.Measures[@"Adherence 60 Day"] : mt.AddMeasure(@"Adherence 60 Day");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[Adherent60] = 1, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[Adherent60])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])), 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Adherence 60 Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Adherence 90 Day") ? mt.Measures[@"Adherence 90 Day"] : mt.AddMeasure(@"Adherence 90 Day");
    m.Expression = @"DIVIDE(
    CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[Adherent90] = 1, USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])),
    CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[Adherent90])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date])), 0)";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Adherence 90 Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandoned Pre PA") ? mt.Measures[@"Abandoned Pre PA"] : mt.AddMeasure(@"Abandoned Pre PA");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[IsAbandoned] = 1, FactPatientCases[AbandonmentStage] = ""Pre-PA"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandoned Pre PA -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandoned During PA") ? mt.Measures[@"Abandoned During PA"] : mt.AddMeasure(@"Abandoned During PA");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[IsAbandoned] = 1, FactPatientCases[AbandonmentStage] = ""During PA"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandoned During PA -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandoned Post PA") ? mt.Measures[@"Abandoned Post PA"] : mt.AddMeasure(@"Abandoned Post PA");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[IsAbandoned] = 1, FactPatientCases[AbandonmentStage] = ""Post-PA"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandoned Post PA -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandoned Post Fulfillment") ? mt.Measures[@"Abandoned Post Fulfillment"] : mt.AddMeasure(@"Abandoned Post Fulfillment");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[IsAbandoned] = 1, FactPatientCases[AbandonmentStage] = ""Post-Fulfillment"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Support";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandoned Post Fulfillment -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg AHT") ? mt.Measures[@"Avg AHT"] : mt.AddMeasure(@"Avg AHT");
    m.Expression = @"AVERAGE(FactHCPCalls[AHT_Minutes])";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg AHT -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg After Call Work") ? mt.Measures[@"Avg After Call Work"] : mt.AddMeasure(@"Avg After Call Work");
    m.Expression = @"AVERAGE(FactHCPCalls[AfterCallWorkMinutes])";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg After Call Work -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Schedule Adherence Rate") ? mt.Measures[@"Schedule Adherence Rate"] : mt.AddMeasure(@"Schedule Adherence Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[IsScheduleAdherent] = 1), [Total Calls], 0)";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Schedule Adherence Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls Per Rep Per Day") ? mt.Measures[@"Calls Per Rep Per Day"] : mt.AddMeasure(@"Calls Per Rep Per Day");
    m.Expression = @"DIVIDE([Total Calls], DISTINCTCOUNT(FactHCPCalls[RepID]) * DISTINCTCOUNT(FactHCPCalls[CallDate]), 0)";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls Per Rep Per Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connected Calls Per Rep Per Day") ? mt.Measures[@"Connected Calls Per Rep Per Day"] : mt.AddMeasure(@"Connected Calls Per Rep Per Day");
    m.Expression = @"DIVIDE([Connected Calls], DISTINCTCOUNT(FactHCPCalls[RepID]) * DISTINCTCOUNT(FactHCPCalls[CallDate]), 0)";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connected Calls Per Rep Per Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Meaningful Per Rep Per Day") ? mt.Measures[@"Meaningful Per Rep Per Day"] : mt.AddMeasure(@"Meaningful Per Rep Per Day");
    m.Expression = @"DIVIDE([Meaningful Interactions], DISTINCTCOUNT(FactHCPCalls[RepID]) * DISTINCTCOUNT(FactHCPCalls[CallDate]), 0)";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Meaningful Per Rep Per Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Notes Compliance Rate") ? mt.Measures[@"Notes Compliance Rate"] : mt.AddMeasure(@"Notes Compliance Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[NotesTaken] = 1), [Connected Calls], 0)";
    m.DisplayFolder = @"Ops Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Notes Compliance Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Rx") ? mt.Measures[@"Total Rx"] : mt.AddMeasure(@"Total Rx");
    m.Expression = @"CALCULATE(COUNTROWS(FactRx), USERELATIONSHIP(FactRx[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Rx -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"New to Brand Rx") ? mt.Measures[@"New to Brand Rx"] : mt.AddMeasure(@"New to Brand Rx");
    m.Expression = @"CALCULATE(COUNTROWS(FactRx), FactRx[IsNewToBrand] = 1, USERELATIONSHIP(FactRx[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: New to Brand Rx -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"NBRx Rate") ? mt.Measures[@"NBRx Rate"] : mt.AddMeasure(@"NBRx Rate");
    m.Expression = @"DIVIDE([New to Brand Rx], [Total Rx], 0)";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: NBRx Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Rx Per HCP") ? mt.Measures[@"Rx Per HCP"] : mt.AddMeasure(@"Rx Per HCP");
    m.Expression = @"DIVIDE([Total Rx], DISTINCTCOUNT(FactRx[HCPID]), 0)
Rx from Engaged HCPs =";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Rx Per HCP -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"VAR EngagedHCPs") ? mt.Measures[@"VAR EngagedHCPs"] : mt.AddMeasure(@"VAR EngagedHCPs");
    m.Expression = @"CALCULATETABLE(VALUES(FactHCPCalls[HCPID]), FactHCPCalls[IsConnected] = 1)
RETURN CALCULATE(COUNTROWS(FactRx), USERELATIONSHIP(FactRx[RxDate], DimCalendar[Date]), TREATAS(EngagedHCPs, FactRx[HCPID]))";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: VAR EngagedHCPs -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Rx from Non-Engaged HCPs") ? mt.Measures[@"Rx from Non-Engaged HCPs"] : mt.AddMeasure(@"Rx from Non-Engaged HCPs");
    m.Expression = @"[Total Rx] - [Rx from Engaged HCPs]
NBRx from Engaged HCPs =";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Rx from Non-Engaged HCPs -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"VAR EngagedHCPs") ? mt.Measures[@"VAR EngagedHCPs"] : mt.AddMeasure(@"VAR EngagedHCPs");
    m.Expression = @"CALCULATETABLE(VALUES(FactHCPCalls[HCPID]), FactHCPCalls[IsConnected] = 1)
RETURN CALCULATE(COUNTROWS(FactRx), FactRx[IsNewToBrand] = 1, USERELATIONSHIP(FactRx[RxDate], DimCalendar[Date]), TREATAS(EngagedHCPs, FactRx[HCPID]))";
    m.DisplayFolder = @"Prescriptions";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: VAR EngagedHCPs -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total MSL Queries") ? mt.Measures[@"Total MSL Queries"] : mt.AddMeasure(@"Total MSL Queries");
    m.Expression = @"CALCULATE(COUNTROWS(FactMSLPartnerUsage), USERELATIONSHIP(FactMSLPartnerUsage[UsageDate], DimCalendar[Date]))";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total MSL Queries -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"MSL Queries Per Day") ? mt.Measures[@"MSL Queries Per Day"] : mt.AddMeasure(@"MSL Queries Per Day");
    m.Expression = @"DIVIDE([Total MSL Queries], DISTINCTCOUNT(FactMSLPartnerUsage[UsageDate]), 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: MSL Queries Per Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"MSL Queries Per MSL Per Day") ? mt.Measures[@"MSL Queries Per MSL Per Day"] : mt.AddMeasure(@"MSL Queries Per MSL Per Day");
    m.Expression = @"DIVIDE([Total MSL Queries], DISTINCTCOUNT(FactMSLPartnerUsage[RepID]) * DISTINCTCOUNT(FactMSLPartnerUsage[UsageDate]), 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: MSL Queries Per MSL Per Day -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Fully Answered Rate") ? mt.Measures[@"Fully Answered Rate"] : mt.AddMeasure(@"Fully Answered Rate");
    m.Expression = @"DIVIDE(CALCULATE(COUNTROWS(FactMSLPartnerUsage), FactMSLPartnerUsage[AnswerQuality] = ""Fully Answered""), [Total MSL Queries], 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Fully Answered Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Partially Answered Rate") ? mt.Measures[@"Partially Answered Rate"] : mt.AddMeasure(@"Partially Answered Rate");
    m.Expression = @"DIVIDE(CALCULATE(COUNTROWS(FactMSLPartnerUsage), FactMSLPartnerUsage[AnswerQuality] = ""Partially Answered""), [Total MSL Queries], 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Partially Answered Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"No Answer Rate") ? mt.Measures[@"No Answer Rate"] : mt.AddMeasure(@"No Answer Rate");
    m.Expression = @"DIVIDE(CALCULATE(COUNTROWS(FactMSLPartnerUsage), FactMSLPartnerUsage[AnswerQuality] = ""No Answer Found""), [Total MSL Queries], 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: No Answer Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Time to Answer Sec") ? mt.Measures[@"Avg Time to Answer Sec"] : mt.AddMeasure(@"Avg Time to Answer Sec");
    m.Expression = @"AVERAGE(FactMSLPartnerUsage[TimeToAnswerSec])";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Time to Answer Sec -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Time Saved Hours") ? mt.Measures[@"Total Time Saved Hours"] : mt.AddMeasure(@"Total Time Saved Hours");
    m.Expression = @"DIVIDE(SUM(FactMSLPartnerUsage[TimeSavedMinutes]), 60, 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Time Saved Hours -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Time Saved Per Query Min") ? mt.Measures[@"Avg Time Saved Per Query Min"] : mt.AddMeasure(@"Avg Time Saved Per Query Min");
    m.Expression = @"AVERAGE(FactMSLPartnerUsage[TimeSavedMinutes])";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Time Saved Per Query Min -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Used in HCP Interaction Rate") ? mt.Measures[@"Used in HCP Interaction Rate"] : mt.AddMeasure(@"Used in HCP Interaction Rate");
    m.Expression = @"DIVIDE(CALCULATE(COUNTROWS(FactMSLPartnerUsage), FactMSLPartnerUsage[UsedInHCPInteraction] = 1), [Total MSL Queries], 0)";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Used in HCP Interaction Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg MSL Satisfaction") ? mt.Measures[@"Avg MSL Satisfaction"] : mt.AddMeasure(@"Avg MSL Satisfaction");
    m.Expression = @"AVERAGE(FactMSLPartnerUsage[UserSatisfaction])";
    m.DisplayFolder = @"MSL Partner Usage";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg MSL Satisfaction -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Experiments") ? mt.Measures[@"Total Experiments"] : mt.AddMeasure(@"Total Experiments");
    m.Expression = @"COUNTROWS(DimExperiment)";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Experiments -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Concluded Experiments") ? mt.Measures[@"Concluded Experiments"] : mt.AddMeasure(@"Concluded Experiments");
    m.Expression = @"CALCULATE(COUNTROWS(DimExperiment), LEFT(DimExperiment[Status], 9) = ""Concluded"")";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Concluded Experiments -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Running Experiments") ? mt.Measures[@"Running Experiments"] : mt.AddMeasure(@"Running Experiments");
    m.Expression = @"CALCULATE(COUNTROWS(DimExperiment), DimExperiment[Status] = ""Running"")";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Running Experiments -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Win Rate") ? mt.Measures[@"Win Rate"] : mt.AddMeasure(@"Win Rate");
    m.Expression = @"DIVIDE(CALCULATE(COUNTROWS(DimExperiment), DimExperiment[Status] = ""Concluded - Winner""), [Concluded Experiments], 0)";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Win Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Observed Lift") ? mt.Measures[@"Avg Observed Lift"] : mt.AddMeasure(@"Avg Observed Lift");
    m.Expression = @"CALCULATE(AVERAGE(DimExperiment[ObservedLift]), DimExperiment[Status] = ""Concluded - Winner"")";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Observed Lift -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Experiment Lift") ? mt.Measures[@"Experiment Lift"] : mt.AddMeasure(@"Experiment Lift");
    m.Expression = @"AVERAGE(DimExperiment[ObservedLift])";
    m.DisplayFolder = @"Experiment Tracking";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Experiment Lift -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Revenue USD") ? mt.Measures[@"Total Revenue USD"] : mt.AddMeasure(@"Total Revenue USD");
    m.Expression = @"SUM(FactFinancials[TotalRevenue_USD])";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Revenue USD -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Cost EUR") ? mt.Measures[@"Total Cost EUR"] : mt.AddMeasure(@"Total Cost EUR");
    m.Expression = @"SUM(FactFinancials[TotalCost_EUR])";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Cost EUR -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Gross Margin USD") ? mt.Measures[@"Gross Margin USD"] : mt.AddMeasure(@"Gross Margin USD");
    m.Expression = @"SUM(FactFinancials[GrossMargin_USD])";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Gross Margin USD -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Gross Margin Pct") ? mt.Measures[@"Gross Margin Pct"] : mt.AddMeasure(@"Gross Margin Pct");
    m.Expression = @"DIVIDE([Gross Margin USD], [Total Revenue USD], 0)";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Gross Margin Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Cost Per Call") ? mt.Measures[@"Avg Cost Per Call"] : mt.AddMeasure(@"Avg Cost Per Call");
    m.Expression = @"AVERAGE(FactFinancials[CostPerCall_EUR])";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Cost Per Call -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Cost Per Case") ? mt.Measures[@"Avg Cost Per Case"] : mt.AddMeasure(@"Avg Cost Per Case");
    m.Expression = @"AVERAGE(FactFinancials[CostPerCase_EUR])";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Cost Per Case -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cost Breakdown Rep Pct") ? mt.Measures[@"Cost Breakdown Rep Pct"] : mt.AddMeasure(@"Cost Breakdown Rep Pct");
    m.Expression = @"DIVIDE(SUM(FactFinancials[RepCost_EUR]), [Total Cost EUR], 0)";
    m.DisplayFolder = @"Financials";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cost Breakdown Rep Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls L4W") ? mt.Measures[@"Calls L4W"] : mt.AddMeasure(@"Calls L4W");
    m.Expression = @"CALCULATE([Total Calls], DATESINPERIOD(DimCalendar[Date], MAX(DimCalendar[Date]), -28, DAY))";
    m.DisplayFolder = @"Time Intelligence";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls L4W -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate L4W") ? mt.Measures[@"Connect Rate L4W"] : mt.AddMeasure(@"Connect Rate L4W");
    m.Expression = @"CALCULATE([Connect Rate], DATESINPERIOD(DimCalendar[Date], MAX(DimCalendar[Date]), -28, DAY))";
    m.DisplayFolder = @"Time Intelligence";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate L4W -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls MoM Change") ? mt.Measures[@"Calls MoM Change"] : mt.AddMeasure(@"Calls MoM Change");
    m.Expression = @"VAR Current = [Total Calls] VAR Prior = CALCULATE([Total Calls], DATEADD(DimCalendar[Date], -1, MONTH)) RETURN DIVIDE(Current - Prior, Prior, 0)";
    m.DisplayFolder = @"Time Intelligence";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls MoM Change -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate MoM Change") ? mt.Measures[@"Connect Rate MoM Change"] : mt.AddMeasure(@"Connect Rate MoM Change");
    m.Expression = @"[Connect Rate] - CALCULATE([Connect Rate], DATEADD(DimCalendar[Date], -1, MONTH))";
    m.DisplayFolder = @"Time Intelligence";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate MoM Change -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandonment Rate MoM Change") ? mt.Measures[@"Abandonment Rate MoM Change"] : mt.AddMeasure(@"Abandonment Rate MoM Change");
    m.Expression = @"[Abandonment Rate] - CALCULATE([Abandonment Rate], DATEADD(DimCalendar[Date], -1, MONTH))";
    m.DisplayFolder = @"Time Intelligence";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandonment Rate MoM Change -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script Deviation Rate") ? mt.Measures[@"Script Deviation Rate"] : mt.AddMeasure(@"Script Deviation Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[ScriptDeviation] = 1), [Connected Calls], 0)";
    m.DisplayFolder = @"Compliance & Quality";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script Deviation Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Call Quality Score") ? mt.Measures[@"Avg Call Quality Score"] : mt.AddMeasure(@"Avg Call Quality Score");
    m.Expression = @"CALCULATE(AVERAGE(FactHCPCalls[CallQualityScore]), NOT(ISBLANK(FactHCPCalls[CallQualityScore])))";
    m.DisplayFolder = @"Compliance & Quality";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Call Quality Score -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"AE Flag Rate") ? mt.Measures[@"AE Flag Rate"] : mt.AddMeasure(@"AE Flag Rate");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[AdverseEventFlagged] = 1), [Connected Calls], 0)";
    m.DisplayFolder = @"Compliance & Quality";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: AE Flag Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"High Quality Calls Pct") ? mt.Measures[@"High Quality Calls Pct"] : mt.AddMeasure(@"High Quality Calls Pct");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[CallQualityScore] >= 7), CALCULATE([Total Calls], NOT(ISBLANK(FactHCPCalls[CallQualityScore]))), 0)";
    m.DisplayFolder = @"Compliance & Quality";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: High Quality Calls Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Low Quality Calls Pct") ? mt.Measures[@"Low Quality Calls Pct"] : mt.AddMeasure(@"Low Quality Calls Pct");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[CallQualityScore] <= 4), CALCULATE([Total Calls], NOT(ISBLANK(FactHCPCalls[CallQualityScore]))), 0)";
    m.DisplayFolder = @"Compliance & Quality";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Low Quality Calls Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Quality Adjusted Productivity") ? mt.Measures[@"Quality Adjusted Productivity"] : mt.AddMeasure(@"Quality Adjusted Productivity");
    m.Expression = @"[Meaningful Per Rep Per Day] * [Avg Call Quality Score] / 10";
    m.DisplayFolder = @"Workforce Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Quality Adjusted Productivity -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Utilization Rate") ? mt.Measures[@"Utilization Rate"] : mt.AddMeasure(@"Utilization Rate");
    m.Expression = @"DIVIDE([Total Calls] * [Avg AHT], DISTINCTCOUNT(FactHCPCalls[RepID]) * DISTINCTCOUNT(FactHCPCalls[CallDate]) * 480, 0)";
    m.DisplayFolder = @"Workforce Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Utilization Rate -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls Per Productive Hour") ? mt.Measures[@"Calls Per Productive Hour"] : mt.AddMeasure(@"Calls Per Productive Hour");
    m.Expression = @"DIVIDE([Total Calls], [Total Calls] * [Avg AHT] / 60, 0)";
    m.DisplayFolder = @"Workforce Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls Per Productive Hour -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Deviation Rate by Tenure") ? mt.Measures[@"Deviation Rate by Tenure"] : mt.AddMeasure(@"Deviation Rate by Tenure");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[ScriptDeviation] = 1), [Total Calls], 0)";
    m.DisplayFolder = @"Workforce Efficiency";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Deviation Rate by Tenure -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Phone Calls Pct") ? mt.Measures[@"Phone Calls Pct"] : mt.AddMeasure(@"Phone Calls Pct");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Channel] = ""Phone""), [Total Calls], 0)";
    m.DisplayFolder = @"Channel Mix";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Phone Calls Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Email Pct") ? mt.Measures[@"Email Pct"] : mt.AddMeasure(@"Email Pct");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Channel] = ""Email""), [Total Calls], 0)";
    m.DisplayFolder = @"Channel Mix";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Email Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Video Pct") ? mt.Measures[@"Video Pct"] : mt.AddMeasure(@"Video Pct");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Channel] = ""Video""), [Total Calls], 0)";
    m.DisplayFolder = @"Channel Mix";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Video Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate by Channel Phone") ? mt.Measures[@"Connect Rate by Channel Phone"] : mt.AddMeasure(@"Connect Rate by Channel Phone");
    m.Expression = @"DIVIDE(CALCULATE([Total Calls], FactHCPCalls[Channel] = ""Phone"", FactHCPCalls[IsConnected] = 1), CALCULATE([Total Calls], FactHCPCalls[Channel] = ""Phone""), 0)";
    m.DisplayFolder = @"Channel Mix";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate by Channel Phone -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate RAG") ? mt.Measures[@"Connect Rate RAG"] : mt.AddMeasure(@"Connect Rate RAG");
    m.Expression = @"SWITCH(TRUE(), [Connect Rate] >= 0.35, ""Green"", [Connect Rate] >= 0.25, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Abandonment Rate RAG") ? mt.Measures[@"Abandonment Rate RAG"] : mt.AddMeasure(@"Abandonment Rate RAG");
    m.Expression = @"SWITCH(TRUE(), [Abandonment Rate] <= 0.15, ""Green"", [Abandonment Rate] <= 0.25, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Abandonment Rate RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Time to Therapy RAG") ? mt.Measures[@"Time to Therapy RAG"] : mt.AddMeasure(@"Time to Therapy RAG");
    m.Expression = @"SWITCH(TRUE(), [Avg Time to Therapy] <= 20, ""Green"", [Avg Time to Therapy] <= 35, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Time to Therapy RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"PA Approval Rate RAG") ? mt.Measures[@"PA Approval Rate RAG"] : mt.AddMeasure(@"PA Approval Rate RAG");
    m.Expression = @"SWITCH(TRUE(), [PA Approval Rate] >= 0.70, ""Green"", [PA Approval Rate] >= 0.55, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: PA Approval Rate RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Schedule Adherence RAG") ? mt.Measures[@"Schedule Adherence RAG"] : mt.AddMeasure(@"Schedule Adherence RAG");
    m.Expression = @"SWITCH(TRUE(), [Schedule Adherence Rate] >= 0.85, ""Green"", [Schedule Adherence Rate] >= 0.75, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Schedule Adherence RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"MSL Answer Quality RAG") ? mt.Measures[@"MSL Answer Quality RAG"] : mt.AddMeasure(@"MSL Answer Quality RAG");
    m.Expression = @"SWITCH(TRUE(), [Fully Answered Rate] >= 0.70, ""Green"", [Fully Answered Rate] >= 0.55, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: MSL Answer Quality RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Script Deviation RAG") ? mt.Measures[@"Script Deviation RAG"] : mt.AddMeasure(@"Script Deviation RAG");
    m.Expression = @"SWITCH(TRUE(), [Script Deviation Rate] <= 0.05, ""Green"", [Script Deviation Rate] <= 0.15, ""Amber"", ""Red"")";
    m.DisplayFolder = @"RAG Indicators";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Script Deviation RAG -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Days Rx to Contact") ? mt.Measures[@"Avg Days Rx to Contact"] : mt.AddMeasure(@"Avg Days Rx to Contact");
    m.Expression = @"CALCULATE(AVERAGEX(FactPatientCases, DATEDIFF(FactPatientCases[RxDate], FactPatientCases[FirstContactDate], DAY)), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Access Bottleneck";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Days Rx to Contact -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Days Contact to PA Submit") ? mt.Measures[@"Avg Days Contact to PA Submit"] : mt.AddMeasure(@"Avg Days Contact to PA Submit");
    m.Expression = @"CALCULATE(AVERAGEX(FactPatientCases, DATEDIFF(FactPatientCases[FirstContactDate], FactPatientCases[PASubmitDate], DAY)), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Access Bottleneck";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Days Contact to PA Submit -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Days PA Submit to Decision") ? mt.Measures[@"Avg Days PA Submit to Decision"] : mt.AddMeasure(@"Avg Days PA Submit to Decision");
    m.Expression = @"CALCULATE(AVERAGEX(FILTER(FactPatientCases, NOT(ISBLANK(FactPatientCases[PADecisionDate]))), DATEDIFF(FactPatientCases[PASubmitDate], FactPatientCases[PADecisionDate], DAY)), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Access Bottleneck";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Days PA Submit to Decision -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Days Decision to Fulfillment") ? mt.Measures[@"Avg Days Decision to Fulfillment"] : mt.AddMeasure(@"Avg Days Decision to Fulfillment");
    m.Expression = @"CALCULATE(AVERAGEX(FILTER(FactPatientCases, NOT(ISBLANK(FactPatientCases[FulfillmentDate]))), DATEDIFF(FactPatientCases[PADecisionDate], FactPatientCases[FulfillmentDate], DAY)), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Access Bottleneck";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Days Decision to Fulfillment -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Days Fulfillment to First Dose") ? mt.Measures[@"Avg Days Fulfillment to First Dose"] : mt.AddMeasure(@"Avg Days Fulfillment to First Dose");
    m.Expression = @"CALCULATE(AVERAGEX(FILTER(FactPatientCases, NOT(ISBLANK(FactPatientCases[FirstDoseDate]))), DATEDIFF(FactPatientCases[FulfillmentDate], FactPatientCases[FirstDoseDate], DAY)), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Access Bottleneck";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Days Fulfillment to First Dose -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Total Handling Minutes") ? mt.Measures[@"Total Handling Minutes"] : mt.AddMeasure(@"Total Handling Minutes");
    m.Expression = @"SUM(FactHCPCalls[AHT_Minutes])";
    m.DisplayFolder = @"Selling Time vs Admin";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Total Handling Minutes -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Selling Minutes") ? mt.Measures[@"Selling Minutes"] : mt.AddMeasure(@"Selling Minutes");
    m.Expression = @"CALCULATE(SUM(FactHCPCalls[DurationMinutes]), FactHCPCalls[IsConnected] = 1)";
    m.DisplayFolder = @"Selling Time vs Admin";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Selling Minutes -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Selling Time Pct") ? mt.Measures[@"Selling Time Pct"] : mt.AddMeasure(@"Selling Time Pct");
    m.Expression = @"DIVIDE([Selling Minutes], [Total Handling Minutes], 0)";
    m.DisplayFolder = @"Selling Time vs Admin";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Selling Time Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Admin Time Pct") ? mt.Measures[@"Admin Time Pct"] : mt.AddMeasure(@"Admin Time Pct");
    m.Expression = @"DIVIDE(SUM(FactHCPCalls[AfterCallWorkMinutes]), [Total Handling Minutes], 0)";
    m.DisplayFolder = @"Selling Time vs Admin";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Admin Time Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Positive Sentiment Pct") ? mt.Measures[@"Positive Sentiment Pct"] : mt.AddMeasure(@"Positive Sentiment Pct");
    m.Expression = @"DIVIDE(
    CALCULATE([Total Calls], FactHCPCalls[SentimentBand] = ""Positive""),
    CALCULATE([Total Calls], NOT(ISBLANK(FactHCPCalls[HCPSentimentScore]))), 0)";
    m.DisplayFolder = @"Sentiment & Insight Engine";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Positive Sentiment Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Negative Sentiment Pct") ? mt.Measures[@"Negative Sentiment Pct"] : mt.AddMeasure(@"Negative Sentiment Pct");
    m.Expression = @"DIVIDE(
    CALCULATE([Total Calls], FactHCPCalls[SentimentBand] = ""Negative""),
    CALCULATE([Total Calls], NOT(ISBLANK(FactHCPCalls[HCPSentimentScore]))), 0)";
    m.DisplayFolder = @"Sentiment & Insight Engine";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Negative Sentiment Pct -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Uplift") ? mt.Measures[@"Avg Uplift"] : mt.AddMeasure(@"Avg Uplift");
    m.Expression = @"AVERAGE(FactUplift[uplift])";
    m.DisplayFolder = @"Sentiment & Insight Engine";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Uplift -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Importance") ? mt.Measures[@"Avg Importance"] : mt.AddMeasure(@"Avg Importance");
    m.Expression = @"AVERAGE(FeatureImportance[importance])";
    m.DisplayFolder = @"Sentiment & Insight Engine";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Importance -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Avg Shap Importance") ? mt.Measures[@"Avg Shap Importance"] : mt.AddMeasure(@"Avg Shap Importance");
    m.Expression = @"AVERAGE(ShapImportance[mean_abs_shap])";
    m.DisplayFolder = @"Sentiment & Insight Engine";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Avg Shap Importance -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Last Data Date") ? mt.Measures[@"Last Data Date"] : mt.AddMeasure(@"Last Data Date");
    m.Expression = @"CALCULATE(MAX(FactHCPCalls[CallDate]), ALL(FactHCPCalls), ALL(DimCalendar))";
    m.DisplayFolder = @"Recent Activity — as-of latest data date";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Last Data Date -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls Last 7 Days") ? mt.Measures[@"Calls Last 7 Days"] : mt.AddMeasure(@"Calls Last 7 Days");
    m.Expression = @"CALCULATE([Total Calls], DATESINPERIOD(DimCalendar[Date], [Last Data Date], -7, DAY))";
    m.DisplayFolder = @"Recent Activity — as-of latest data date";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls Last 7 Days -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls Prior 7 Days") ? mt.Measures[@"Calls Prior 7 Days"] : mt.AddMeasure(@"Calls Prior 7 Days");
    m.Expression = @"CALCULATE([Total Calls], DATESINPERIOD(DimCalendar[Date], [Last Data Date] - 7, -7, DAY))";
    m.DisplayFolder = @"Recent Activity — as-of latest data date";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls Prior 7 Days -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Calls WoW Change") ? mt.Measures[@"Calls WoW Change"] : mt.AddMeasure(@"Calls WoW Change");
    m.Expression = @"DIVIDE([Calls Last 7 Days] - [Calls Prior 7 Days], [Calls Prior 7 Days], 0)";
    m.DisplayFolder = @"Recent Activity — as-of latest data date";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Calls WoW Change -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Connect Rate Last 7 Days") ? mt.Measures[@"Connect Rate Last 7 Days"] : mt.AddMeasure(@"Connect Rate Last 7 Days");
    m.Expression = @"CALCULATE([Connect Rate], DATESINPERIOD(DimCalendar[Date], [Last Data Date], -7, DAY))";
    m.DisplayFolder = @"Recent Activity — as-of latest data date";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Connect Rate Last 7 Days -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cases First Contacted") ? mt.Measures[@"Cases First Contacted"] : mt.AddMeasure(@"Cases First Contacted");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[FirstContactDate])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Funnel Stage Counts";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cases First Contacted -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cases PA Submitted") ? mt.Measures[@"Cases PA Submitted"] : mt.AddMeasure(@"Cases PA Submitted");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[PASubmitDate])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Funnel Stage Counts";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cases PA Submitted -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cases PA Approved") ? mt.Measures[@"Cases PA Approved"] : mt.AddMeasure(@"Cases PA Approved");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[PAStatus] = ""Approved"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Funnel Stage Counts";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cases PA Approved -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cases Fulfilled") ? mt.Measures[@"Cases Fulfilled"] : mt.AddMeasure(@"Cases Fulfilled");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[FulfillmentDate])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Funnel Stage Counts";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cases Fulfilled -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Cases On Therapy") ? mt.Measures[@"Cases On Therapy"] : mt.AddMeasure(@"Cases On Therapy");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), NOT(ISBLANK(FactPatientCases[FirstDoseDate])), USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Patient Funnel Stage Counts";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Cases On Therapy -> " + ex.Message); }
try {
    var m = mt.Measures.Contains(@"Open High Risk Cases") ? mt.Measures[@"Open High Risk Cases"] : mt.AddMeasure(@"Open High Risk Cases");
    m.Expression = @"CALCULATE(COUNTROWS(FactPatientCases), FactPatientCases[Open Case Age Bucket] = ""14d+"", USERELATIONSHIP(FactPatientCases[RxDate], DimCalendar[Date]))";
    m.DisplayFolder = @"Open-Case Aging";
    mAdded++;
} catch (Exception ex) { Info("Measure failed: Open High Risk Cases -> " + ex.Message); }

// ---- Calculated columns ----
try {
    var t = Model.Tables["DimRep"];
    if (!t.Columns.Contains(@"Performance Tier")) t.AddCalculatedColumn(@"Performance Tier", @"VAR Total = COUNTROWS(ALL(DimRep))
VAR Rnk = RANKX(ALL(DimRep), CALCULATE([Meaningful Interactions]), , DESC)
RETURN IF(Rnk <= ROUNDUP(Total * 0.2, 0), ""Top 20%"", ""Rest"")");
    else ((CalculatedColumn)t.Columns[@"Performance Tier"]).Expression = @"VAR Total = COUNTROWS(ALL(DimRep))
VAR Rnk = RANKX(ALL(DimRep), CALCULATE([Meaningful Interactions]), , DESC)
RETURN IF(Rnk <= ROUNDUP(Total * 0.2, 0), ""Top 20%"", ""Rest"")";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: Performance Tier -> " + ex.Message); }
try {
    var t = Model.Tables["DimRep"];
    if (!t.Columns.Contains(@"Tenure Bucket")) t.AddCalculatedColumn(@"Tenure Bucket", @"SWITCH(TRUE(),
    DimRep[TenureMonths] < 6, ""0-6mo"",
    DimRep[TenureMonths] < 12, ""6-12mo"",
    DimRep[TenureMonths] < 18, ""12-18mo"",
    ""18+mo"")");
    else ((CalculatedColumn)t.Columns[@"Tenure Bucket"]).Expression = @"SWITCH(TRUE(),
    DimRep[TenureMonths] < 6, ""0-6mo"",
    DimRep[TenureMonths] < 12, ""6-12mo"",
    DimRep[TenureMonths] < 18, ""12-18mo"",
    ""18+mo"")";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: Tenure Bucket -> " + ex.Message); }
try {
    var t = Model.Tables["FactHCPCalls"];
    if (!t.Columns.Contains(@"CallTimeBucket")) t.AddCalculatedColumn(@"CallTimeBucket", @"VAR h = VALUE(LEFT(FactHCPCalls[CallTime], 2))
RETURN SWITCH(TRUE(), h < 18, ""16-18"", h < 20, ""18-20"", h < 22, ""20-22"", ""22-00"")");
    else ((CalculatedColumn)t.Columns[@"CallTimeBucket"]).Expression = @"VAR h = VALUE(LEFT(FactHCPCalls[CallTime], 2))
RETURN SWITCH(TRUE(), h < 18, ""16-18"", h < 20, ""18-20"", h < 22, ""20-22"", ""22-00"")";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: CallTimeBucket -> " + ex.Message); }
try {
    var t = Model.Tables["FactHCPCalls"];
    if (!t.Columns.Contains(@"SentimentBand")) t.AddCalculatedColumn(@"SentimentBand", @"SWITCH(TRUE(),
    ISBLANK(FactHCPCalls[HCPSentimentScore]), BLANK(),
    FactHCPCalls[HCPSentimentScore] >= 4, ""Positive"",
    FactHCPCalls[HCPSentimentScore] >= 2.5, ""Neutral"",
    ""Negative"")");
    else ((CalculatedColumn)t.Columns[@"SentimentBand"]).Expression = @"SWITCH(TRUE(),
    ISBLANK(FactHCPCalls[HCPSentimentScore]), BLANK(),
    FactHCPCalls[HCPSentimentScore] >= 4, ""Positive"",
    FactHCPCalls[HCPSentimentScore] >= 2.5, ""Neutral"",
    ""Negative"")";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: SentimentBand -> " + ex.Message); }
try {
    var t = Model.Tables["FactPatientCases"];
    if (!t.Columns.Contains(@"Open Case Age Bucket")) t.AddCalculatedColumn(@"Open Case Age Bucket", @"VAR AsOf = CALCULATE(MAX(FactHCPCalls[CallDate]), ALL(FactHCPCalls))
VAR d = DATEDIFF(FactPatientCases[RxDate], AsOf, DAY)
RETURN IF(NOT(FactPatientCases[CaseStatus] IN {""Open"", ""In Progress""}), BLANK(),
    SWITCH(TRUE(), d < 3, ""<3d"", d < 7, ""3-7d"", d < 14, ""7-14d"", ""14d+""))");
    else ((CalculatedColumn)t.Columns[@"Open Case Age Bucket"]).Expression = @"VAR AsOf = CALCULATE(MAX(FactHCPCalls[CallDate]), ALL(FactHCPCalls))
VAR d = DATEDIFF(FactPatientCases[RxDate], AsOf, DAY)
RETURN IF(NOT(FactPatientCases[CaseStatus] IN {""Open"", ""In Progress""}), BLANK(),
    SWITCH(TRUE(), d < 3, ""<3d"", d < 7, ""3-7d"", d < 14, ""7-14d"", ""14d+""))";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: Open Case Age Bucket -> " + ex.Message); }
try {
    var t = Model.Tables["DimRep"];
    if (!t.Columns.Contains(@"AI Adoption Band")) t.AddCalculatedColumn(@"AI Adoption Band", @"VAR r = CALCULATE(DIVIDE(CALCULATE(COUNTROWS(FactHCPCalls), FactHCPCalls[AIFollowed] = 1), COUNTROWS(FactHCPCalls)))
RETURN SWITCH(TRUE(), r >= 0.5, ""High"", r >= 0.3, ""Medium"", ""Low"")");
    else ((CalculatedColumn)t.Columns[@"AI Adoption Band"]).Expression = @"VAR r = CALCULATE(DIVIDE(CALCULATE(COUNTROWS(FactHCPCalls), FactHCPCalls[AIFollowed] = 1), COUNTROWS(FactHCPCalls)))
RETURN SWITCH(TRUE(), r >= 0.5, ""High"", r >= 0.3, ""Medium"", ""Low"")";
    cAdded++;
} catch (Exception ex) { Info("Calc column failed: AI Adoption Band -> " + ex.Message); }

// ---- Relationships (Phase 1A) ----
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactHCPCalls"].Columns["CallDate"];
    r.ToColumn = Model.Tables["DimCalendar"].Columns["Date"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactHCPCalls[CallDate]->DimCalendar[Date] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactPatientCases"].Columns["RxDate"];
    r.ToColumn = Model.Tables["DimCalendar"].Columns["Date"];
    r.IsActive = false;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactPatientCases[RxDate]->DimCalendar[Date] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactRx"].Columns["RxDate"];
    r.ToColumn = Model.Tables["DimCalendar"].Columns["Date"];
    r.IsActive = false;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactRx[RxDate]->DimCalendar[Date] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactMSLPartnerUsage"].Columns["UsageDate"];
    r.ToColumn = Model.Tables["DimCalendar"].Columns["Date"];
    r.IsActive = false;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactMSLPartnerUsage[UsageDate]->DimCalendar[Date] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactFinancials"].Columns["MonthDate"];
    r.ToColumn = Model.Tables["DimCalendar"].Columns["Date"];
    r.IsActive = false;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactFinancials[MonthDate]->DimCalendar[Date] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactHCPCalls"].Columns["RepID"];
    r.ToColumn = Model.Tables["DimRep"].Columns["RepID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactHCPCalls[RepID]->DimRep[RepID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactHCPCalls"].Columns["HCPID"];
    r.ToColumn = Model.Tables["DimHCP"].Columns["HCPID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactHCPCalls[HCPID]->DimHCP[HCPID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactPatientCases"].Columns["PatientID"];
    r.ToColumn = Model.Tables["DimPatient"].Columns["PatientID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactPatientCases[PatientID]->DimPatient[PatientID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactPatientCases"].Columns["RepID"];
    r.ToColumn = Model.Tables["DimRep"].Columns["RepID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactPatientCases[RepID]->DimRep[RepID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactRx"].Columns["HCPID"];
    r.ToColumn = Model.Tables["DimHCP"].Columns["HCPID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactRx[HCPID]->DimHCP[HCPID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactMSLPartnerUsage"].Columns["RepID"];
    r.ToColumn = Model.Tables["DimRep"].Columns["RepID"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactMSLPartnerUsage[RepID]->DimRep[RepID] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactHCPCalls"].Columns["Drug"];
    r.ToColumn = Model.Tables["DimDrug"].Columns["DrugName"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactHCPCalls[Drug]->DimDrug[DrugName] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactPatientCases"].Columns["Drug"];
    r.ToColumn = Model.Tables["DimDrug"].Columns["DrugName"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactPatientCases[Drug]->DimDrug[DrugName] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactRx"].Columns["Drug"];
    r.ToColumn = Model.Tables["DimDrug"].Columns["DrugName"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactRx[Drug]->DimDrug[DrugName] -> " + ex.Message); }
try {
    var r = Model.AddRelationship();
    r.FromColumn = Model.Tables["FactMSLPartnerUsage"].Columns["Drug"];
    r.ToColumn = Model.Tables["DimDrug"].Columns["DrugName"];
    r.IsActive = true;
    rAdded++;
} catch (Exception ex) { Info("Relationship failed: FactMSLPartnerUsage[Drug]->DimDrug[DrugName] -> " + ex.Message); }

Info($"Done: {mAdded} measures, {cAdded} calc columns, {rAdded} relationships.");
